version: '3.7'

services:

# Nginx image setup
  nginx:
    container_name: ft_nginx
    build: ./nginx
    image: ft_nginx
    ports:
      - 443:443
    restart: always
    networks: 
      - "inception-network"
    volumes:
      - wordpress_vol:/var/www/jarsenio.com

# wordpress image setup
  wordpress:
    container_name: ft_wordpress
    build: ./wordpress
    image: ft_wordpress
    # ports:
    #   - 9000:9000
    restart: always
    networks:
      - inception-network
    volumes:
      - wordpress_vol:/var/www/jarsenio.com

# Mariadb image setup
  mariadb:
    container_name: ft_mariadb
    build: ./mariadb
    image: ft_mariadb
    # ports:
    #   - 3306:3306
    restart: always
    networks:
      - inception-network
    volumes:
      - mariadb_vol:/var/lib/mysql

    # this environment variables are the container variables
    # so that you can call them inside the container
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
      MARIADB_DATABASE: $MARIADB_DATABASE

volumes:
  mariadb_vol:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb_volume

  wordpress_vol:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress_volume

networks:
  inception-network:
    # driver: bridge