version: '3.7'

services:

# Nginx image setup
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: on-failure
    image: nginx
    ports:
      - 443:443
    networks: 
      - "inception-network"
    volumes:
      - wordpress_vol:/var/www/jarsenio.com

# wordpress image setup
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: on-failure
    env_file:
      - ".env"
    networks:
      - inception-network
    volumes:
      - wordpress_vol:/var/www/jarsenio.com

# Mariadb image setup
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: on-failure
    networks:
      - inception-network
    volumes:
      - mariadb_vol:/var/lib/mysql

    # this environment variables are the container variables
    # so that you can call them inside the container
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}

volumes:
  mariadb_vol:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb_volume

  wordpress_vol:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress_volume

networks:
  inception-network:
    # driver: bridge